/**
 * AI Service — Gemini-powered core engine
 *
 * This is the brain of Path101. No templates, no hardcoded content.
 * Everything is generated by Gemini based on the user's actual needs.
 */

import { GoogleGenerativeAI } from "@google/generative-ai";

const API_KEY = import.meta.env.VITE_GEMINI_API_KEY ?? "";
const genAI = new GoogleGenerativeAI(API_KEY);

const model = genAI.getGenerativeModel({
  model: "gemini-2.0-flash",
  generationConfig: {
    temperature: 0.7,
    maxOutputTokens: 2048,
    responseMimeType: "application/json",
  },
});

const chatModel = genAI.getGenerativeModel({
  model: "gemini-2.0-flash",
  generationConfig: {
    temperature: 0.8,
    maxOutputTokens: 1024,
  },
});

// ── Types ───────────────────────────────────────────

export type AIAnalysis = {
  summary: string;
  concerns: string[];
  emotionalState: string;
  severity: "low" | "medium" | "high" | "crisis";
  suggestedApproach: string;
  safetyAlert: string | null;
};

export type AIStep = {
  title: string;
  description: string;
  durationMins: number;
  type: "exercise" | "reflection" | "action" | "breathing" | "journaling" | "learning";
};

export type AIPlan = {
  title: string;
  goal: string;
  approach: string;
  totalWeeks: number;
  sessionsPerWeek: number;
  sessions: AISession[];
};

export type AISession = {
  id: string;
  title: string;
  description: string;
  durationMins: number;
  difficulty: "gentle" | "moderate" | "challenging";
  steps: AIStep[];
  scheduledDay: string;
};

export type AIReflection = {
  insight: string;
  moodInterpretation: string;
  encouragement: string;
  nextSteps: string;
  journalPrompts: string[];
};

export type AIProgressInsight = {
  overallProgress: string;
  moodTrend: string;
  strengths: string[];
  areasToFocus: string[];
  recommendation: string;
};

// ── Core functions ──────────────────────────────────

/**
 * Deeply analyze the user's input — understand their situation,
 * emotional state, and what kind of help they need.
 */
export async function analyzeUserInput(
  text: string,
  pastContext?: string
): Promise<AIAnalysis> {
  const prompt = `You are Path101, an expert behavioral psychologist and empathetic counselor.

A user has shared what they're going through. Analyze their input deeply.

${pastContext ? `Context from their previous sessions:\n${pastContext}\n` : ""}

User's input: "${text}"

Respond with a JSON object:
{
  "summary": "Brief empathetic summary of what they're experiencing (2-3 sentences)",
  "concerns": ["list", "of", "specific", "concerns", "identified"],
  "emotionalState": "Description of their emotional state",
  "severity": "low | medium | high | crisis",
  "suggestedApproach": "What therapeutic/behavioral approach would help most (be specific)",
  "safetyAlert": null or "If crisis-level, provide crisis resources and immediate guidance"
}

CRITICAL: If the user expresses suicidal ideation, self-harm, or immediate danger, set severity to "crisis" and provide real crisis helpline numbers in safetyAlert. Never ignore safety signals.`;

  const result = await model.generateContent(prompt);
  const json = JSON.parse(result.response.text());
  return json as AIAnalysis;
}

/**
 * Generate a fully personalized plan based on the AI analysis.
 * No templates — every plan is unique to the user.
 */
export async function generatePlan(
  analysis: AIAnalysis,
  availableTimes: string[],
  userPreferences?: string
): Promise<AIPlan> {
  const prompt = `You are Path101, designing a personalized behavior-change micro-intervention plan.

Based on this analysis:
- Summary: ${analysis.summary}
- Concerns: ${analysis.concerns.join(", ")}
- Emotional state: ${analysis.emotionalState}
- Severity: ${analysis.severity}
- Suggested approach: ${analysis.suggestedApproach}

User's available times: ${availableTimes.join(", ")}
${userPreferences ? `Preferences: ${userPreferences}` : ""}

Create a personalized plan. Each session should be 10-25 minutes with actionable, specific steps — NOT generic advice. Include actual exercises, techniques, and activities.

Respond with JSON:
{
  "title": "Plan name that resonates with their situation",
  "goal": "Specific, achievable goal statement",
  "approach": "2-3 sentence explanation of the approach",
  "totalWeeks": 2-6,
  "sessionsPerWeek": 2-4,
  "sessions": [
    {
      "id": "session_1",
      "title": "Specific session name",
      "description": "What this session accomplishes",
      "durationMins": 10-25,
      "difficulty": "gentle | moderate | challenging",
      "steps": [
        {
          "title": "Step name",
          "description": "Detailed instruction — tell them EXACTLY what to do",
          "durationMins": 2-8,
          "type": "exercise | reflection | action | breathing | journaling | learning"
        }
      ],
      "scheduledDay": "Day/time suggestion"
    }
  ]
}

Generate 3-5 sessions. Make them progressive — each session builds on the previous one. Be specific in step descriptions (e.g., "Write down 3 things that went well today" not "Practice gratitude").`;

  const result = await model.generateContent(prompt);
  const json = JSON.parse(result.response.text());
  return json as AIPlan;
}

/**
 * Generate guided content for a specific session step.
 * Called when the user starts a session.
 */
export async function generateStepGuidance(
  step: AIStep,
  sessionContext: string,
  userMood: number
): Promise<string> {
  const prompt = `You are guiding a user through a micro-session step.

Session context: ${sessionContext}
Current step: ${step.title} (${step.type})
User's current mood: ${userMood}/10

Provide warm, clear guidance for this step in 3-5 sentences. Be specific and actionable. Speak directly to the user. Don't be clinical — be supportive and real.`;

  const result = await chatModel.generateContent(prompt);
  return result.response.text();
}

/**
 * Generate AI reflection after a session is completed.
 * Interprets their mood change and provides insight.
 */
export async function generateReflection(
  sessionTitle: string,
  preMood: number,
  postMood: number,
  feedback: string,
  pastSessionCount: number
): Promise<AIReflection> {
  const moodChange = postMood - preMood;
  const prompt = `You are Path101's AI counselor. A user just completed a session.

Session: "${sessionTitle}"
Pre-session mood: ${preMood}/10
Post-session mood: ${postMood}/10
Mood change: ${moodChange > 0 ? `+${moodChange}` : moodChange}
User's feedback: "${feedback}"
This is their session #${pastSessionCount + 1}

Provide a thoughtful, personalized reflection. Be genuine — not generic motivational quotes.

Respond with JSON:
{
  "insight": "What this session revealed about their progress (2-3 sentences)",
  "moodInterpretation": "What their mood change means (acknowledge if it went down too)",
  "encouragement": "Genuine, specific encouragement (not generic praise)",
  "nextSteps": "What to focus on before the next session",
  "journalPrompts": ["3 reflective questions personalized to their experience"]
}`;

  const result = await model.generateContent(prompt);
  const json = JSON.parse(result.response.text());
  return json as AIReflection;
}

/**
 * Generate progress insight from session history.
 */
export async function generateProgressInsight(
  sessions: Array<{ title: string; preMood: number; postMood: number; feedback: string; completedAt: string }>
): Promise<AIProgressInsight> {
  const summary = sessions
    .map((s, i) => `Session ${i + 1}: "${s.title}" | Mood: ${s.preMood}→${s.postMood} | "${s.feedback}"`)
    .join("\n");

  const prompt = `You are Path101's AI counselor analyzing a user's journey.

Their session history:
${summary}

Provide a meaningful progress analysis. Be honest — if progress is mixed, say so. Celebrate real wins.

Respond with JSON:
{
  "overallProgress": "2-3 sentence honest assessment of their journey",
  "moodTrend": "What the mood data reveals",
  "strengths": ["2-3 things they're doing well"],
  "areasToFocus": ["1-2 areas that need attention"],
  "recommendation": "What they should do next"
}`;

  const result = await model.generateContent(prompt);
  const json = JSON.parse(result.response.text());
  return json as AIProgressInsight;
}

/**
 * Quick AI chat — for when the user just wants to talk or ask something.
 */
export async function chat(
  message: string,
  history: Array<{ role: "user" | "assistant"; text: string }>
): Promise<string> {
  const historyPrompt = history
    .map((h) => `${h.role === "user" ? "User" : "Path101"}: ${h.text}`)
    .join("\n");

  const prompt = `You are Path101, an empathetic AI counselor focused on behavioral change for students. You're warm, practical, and evidence-based. Keep responses concise (3-5 sentences unless they ask for more).

${historyPrompt ? `Conversation so far:\n${historyPrompt}\n\n` : ""}User: ${message}

Path101:`;

  const result = await chatModel.generateContent(prompt);
  return result.response.text();
}
